### ISSUE TITLE
unet compute c++ file returns a uint8?

### ISSUE THREAD

**Issue by dillonhuff** [StanfordAHA/Halide-to-Hardware_archive#102]
@jeffsetter One of the unet compute functions returns uint 8 here:

https://github.com/dillonhuff/clockwork/blob/25be48e94e97710c3b8184024a795c43f20c6328/unet_conv_3_3_compute.h#L144

Is this going to be supported on the CGRA? If not could you replace with a function that returns hw_uint<16>?

**Comment by jeffsetter** [comment]
Fixed in https://github.com/dillonhuff/clockwork/pull/48
