### ISSUE TITLE
Discrepancy in casting between pointwise compute .h file and coreir .json

### ISSUE THREAD

**Issue by dillonhuff** [StanfordAHA/Halide-to-Hardware_archive#103]
@jeffsetter I was comparing the cgra pointwise output to the output I get with the coreir and noticed that one of the pointwise compute units casts its output to `uint8`:

https://github.com/dillonhuff/clockwork/blob/b4dc132aa141f610421159bccf8ae21b8ae353ce/pointwise_compute.h#L26

While the corresponding coreir compute uses 16 bit arithmetic in all compute units.

Can this be fixed or am I misunderstanding something about the outputs?

**Comment by jeffsetter** [comment]
We eventually are saving these outputs to 8bit images (typically), and so a cast to 8bits needs to happen somewhere. My coreir testbench always does this 8bit cast when it's needed. I've been moving all of the 8bit casts outside the accelerator, but most of the old compute kernels that have been copied over don't have this yet.

**Comment by dillonhuff** [comment]
@jeffsetter that makes sense. I've just manually changed them to return 16 bits for now. LMK when you update them.
