### ISSUE TITLE
Could you make a single stage, grayscale application that uses a rom?

### ISSUE THREAD

**Issue by dillonhuff** [StanfordAHA/Halide-to-Hardware_archive#106]
@jeffsetter I'd like to have a rom test that is simpler than camera pipeline. Maybe just some pointwise math that looks up something in a ROM?

**Comment by jeffsetter** [comment]
There is a ROM test in apps/hardware_benchmarks/tests/rom that is an isolation of the ROM that exists in camera pipeline. Does that work?
