### ISSUE TITLE
ROM compute uses uint8_t?

### ISSUE THREAD

**Issue by dillonhuff** [StanfordAHA/Halide-to-Hardware_archive#108]
@jeffsetter thanks for adding that ROM example!

However I notice that the CPU and coreir implementations differ starting at output 256 when using the identity stream, and that the rom seems to be 8 bits wide?

**Comment by jeffsetter** [comment]
Interesting, Halide is identifying that the input is 8bits and then that value is used in the ROM. Since the range of values can only be from 0 to 255, it creates a ROM of only length 256. I'll change the clamp between 0 to 255 to fix the ROM size to 256 values.

**Comment by dillonhuff** [comment]
@jeffsetter thanks man!
