### ISSUE TITLE
Typo on clockwork branch in ExtractHWAccelerators.cpp

### ISSUE THREAD

**Issue by jack-melchert** [StanfordAHA/Halide-to-Hardware_archive#93]
https://github.com/StanfordAHA/Halide-to-Hardware/blob/a8f1a59a5b76bd0053861f0823f980b5a7f1488a/src/ExtractHWAccelerators.cpp#L1

Should be #include "ExtractHWAccelerators.h"

**Comment by jeffsetter** [comment]
Fixed.
